create web/mobile strategy, and first class test(move good to box)
MykhailoTsiganko/tautomation pull request #2
Opened 2020-06-24 14:02 UTC by TarasTsyhanko

2020-07-01 10:45 UTC, MykhailoTsiganko requested changes

2020-07-01 10:45 UTC, MykhailoTsiganko commented on src/main/java/bo/BoxBusinessObject.java
> +public class BoxBusinessObject {
rename CartAction

2020-07-01 10:45 UTC, MykhailoTsiganko commented on src/main/java/bo/BoxBusinessObject.java
> +    public void verifySelectedGoodIsInBox(List<String> titlesInBox, String selectedTitle) {
move to CartValidator

2020-07-01 10:45 UTC, MykhailoTsiganko commented on src/main/java/factory/DriverFactory.java
> +        String devise = System.getProperty("devise");
rename to device

2020-07-01 10:45 UTC, MykhailoTsiganko commented on src/main/java/factory/DriverFactory.java
> +    private static WebDriver createWeb(String devise) {
rename to create webDriver

2020-07-01 10:45 UTC, MykhailoTsiganko commented on src/main/java/factory/DriverFactory.java
> +    private static WebDriver createMobile() {
remove

2020-07-01 10:45 UTC, MykhailoTsiganko commented on src/test/java/tests/GoodsInBoxTest.java
> +    @Test
add text description

2020-07-01 14:19 UTC, TarasTsyhanko commented on src/main/java/bo/BoxBusinessObject.java
> +public class BoxBusinessObject {
fixed

2020-07-01 14:19 UTC, TarasTsyhanko commented on src/main/java/bo/BoxBusinessObject.java
> +    public void verifySelectedGoodIsInBox(List<String> titlesInBox, String selectedTitle) {
fixed

2020-07-01 14:19 UTC, TarasTsyhanko commented on src/main/java/factory/DriverFactory.java
> +        String devise = System.getProperty("devise");
fixed

2020-07-01 14:19 UTC, TarasTsyhanko commented on src/main/java/factory/DriverFactory.java
> +    private static WebDriver createWeb(String devise) {
fixed

2020-07-01 14:19 UTC, TarasTsyhanko commented on src/main/java/factory/DriverFactory.java
> +    private static WebDriver createMobile() {
fixed

2020-07-01 14:19 UTC, TarasTsyhanko commented on src/test/java/tests/GoodsInBoxTest.java
> +    @Test
what you mean?
description about test?

2020-07-01 14:39 UTC, MykhailoTsiganko commented on src/test/java/tests/GoodsInBoxTest.java
> +    @Test
@Test(description="description")

2020-07-01 14:47 UTC, TarasTsyhanko commented on src/test/java/tests/GoodsInBoxTest.java
> +    @Test
fixed

2020-07-01 14:53 UTC, MykhailoTsiganko approved these changes

2020-07-01 14:58 UTC, merged

2020-07-06 11:31 UTC, MykhailoTsiganko commented on src/test/java/tests/GoodsInCartTest.java
> +        cartActions = new CartActions();
use @Inject